### ISSUE TITLE
Error when entering a chat on a discorded channel connected to Minecraft server

### ISSUE THREAD

**Issue by Kuass** [woutzah/LiteBansBridge#1]
```
[11:32:26 ERROR]: [DiscordSRV] DiscordSRV API Listener be.woutzah.litebansbridge.listeners.DiscordListener 에서 오류가 발생하였습니다.:java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)        at github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:107)
        at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:197)        at github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:396)
        at github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)        at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
        at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)        at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
        at github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)        at github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:921)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:808)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:786)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:959)
        at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.NullPointerException
        at be.woutzah.litebansbridge.listeners.DiscordListener.afterMessageSend(DiscordListener.java:33)
        ... 23 more
```
If you enter a chat on a discorded channel connected to the Minecraft server, an error occurs every time.

bukkit : paper-90 (1.16.1)
plugins : 
discordsrv 1.19.1
litebansbridge 1.5

**Comment by wouter-blockken** [comment]
Hey there,

Is it possible that you haven't linked your users with DiscordSRV? People have had this issue before and this was their issue.
Let me know if this is the case, otherwise i'll dig into it further

Greets,
Woutzah

**Comment by Kuass** [comment]
Contrary to concerns, we need to link account!
![image](https://user-images.githubusercontent.com/5186106/87551580-889fa700-c6eb-11ea-8818-120215c54ddb.png)

**Comment by Kuass** [comment]
dismissed
